#!/bin/sh

# Run pre-commit if installed
if command -v pre-commit >/dev/null 2>&1; then
  pre-commit run --hook-stage pre-commit
else
  echo "pre-commit not installed, run: pip install pre-commit && pre-commit install"
  exit 1
fi
